/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jyj_myapplication_JniTest */

#ifndef _Included_com_example_jyj_myapplication_JniTest
#define _Included_com_example_jyj_myapplication_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jyj_myapplication_JniTest
 * Method:    getKeyFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jyj_myapplication_JniTest_getKeyFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_example_jyj_myapplication_JniTest
 * Method:    getKeyFromCC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jyj_myapplication_JniTest_getKeyFromCC
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jyj_myapplication_JniTest
 * Method:    accessMethod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_jyj_myapplication_JniTest_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jyj_myapplication_JniTest
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jyj_myapplication_JniTest_accessStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jyj_myapplication_JniTest
 * Method:    accessConstruct
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_com_example_jyj_myapplication_JniTest_accessConstruct
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jyj_myapplication_JniTest
 * Method:    accessNonvirtualMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jyj_myapplication_JniTest_accessNonvirtualMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jyj_myapplication_JniTest
 * Method:    accessChinese
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jyj_myapplication_JniTest_accessChinese
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jyj_myapplication_JniTest
 * Method:    accessIntArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_jyj_myapplication_JniTest_accessIntArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_jyj_myapplication_JniTest
 * Method:    accessReturnArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_jyj_myapplication_JniTest_accessReturnArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_jyj_myapplication_JniTest
 * Method:    accessCatch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jyj_myapplication_JniTest_accessCatch
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jyj_myapplication_JniTest
 * Method:    cacheStrategy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jyj_myapplication_JniTest_cacheStrategy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
